# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_title', models.CharField(blank=True, max_length=300, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=None, width_field='width_field')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('youtube_id', models.CharField(blank=True, max_length=100, null=True)),
                ('playlist_id', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=None, width_field='width_field')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='videos',
            field=models.ManyToManyField(to='courses.Video'),
        ),
    ]
